# Generated by Django 4.1.6 on 2023-10-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_user_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfirmEmailToken',
            new_name='ConfirmToken',
        ),
    ]
