# Generated by Django 4.1.6 on 2023-10-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_confirmemailtoken_confirmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('address', 'Адрес'), ('email', 'Почта'), ('phone', 'Телефон'), ('work_phone', 'Рабочий телефон')], max_length=50, verbose_name='Тип'),
        ),
    ]
